# Generated by Django 4.1.3 on 2023-02-21 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='path',
        ),
        migrations.RemoveField(
            model_name='station',
            name='lockers',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='bicycle_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.station'),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bicycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
