# Generated by Django 4.1.3 on 2023-02-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bicycle_code_remove_bicycle_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='bicycle',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='locker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.locker'),
        ),
        migrations.AddField(
            model_name='locker',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
