# Generated by Django 4.1.3 on 2023-02-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_locker_bicycle_bicycle_locker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='locker_id',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='bicycle_id',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
